### PR TITLE
Add DragSelectCompose

### PR DESCRIPTION
**Pull request by jordond**
Drag-multi-select library [DragSelectCompose](https://github.com/jordond/drag-select-compose)

### CODE REVIEW

**Comment by terrakok** [comment]
I've tried to run the code on iPhone simulator and it doesn't work:
```
Uncaught Kotlin exception: kotlin.IllegalArgumentException: Failed to open iconv for charset UTF-8 with error code 22
    at 0   DragSelectCompose                   0x100d78b03        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 123 
    at 1   DragSelectCompose                   0x100d712d7        kfun:kotlin.Exception#<init>(kotlin.String?){} + 119 
    at 2   DragSelectCompose                   0x100d7167f        kfun:kotlin.RuntimeException#<init>(kotlin.String?){} + 119 
    at 3   DragSelectCompose                   0x100d71a27        kfun:kotlin.IllegalArgumentException#<init>(kotlin.String?){} + 119 
    at 4   DragSelectCompose                   0x10170ebb3        kfun:io.ktor.utils.io.charsets.checkErrors#internal + 815 
    at 5   DragSelectCompose                   0x10170e3e3        kfun:io.ktor.utils.io.charsets.CharsetImpl.<init>#internal + 615 
    at 6   DragSelectCompose                   0x10170b2e3        kfun:io.ktor.utils.io.charsets.Charsets#<init>(){} + 191 
    at 7   DragSelectCompose                   0x10170b1ef        kfun:io.ktor.utils.io.charsets.Charsets.$init_global#internal + 151 
    at 8   DragSelectCompose                   0x101b9056f        CallInitGlobalPossiblyLock + 511 
    at 9   DragSelectCompose                   0x10170b667        kfun:io.ktor.utils.io.charsets.Charsets#<get-$instance>#static(){}io.ktor.utils.io.charsets.Charsets + 99 
    at 10  DragSelectCompose                   0x10173d7ef        kfun:io.ktor.http#encodeURLQueryComponent$default__at__kotlin.String(kotlin.Boolean;kotlin.Boolean;io.ktor.utils.io.charsets.Charset?;kotlin.Int){}kotlin.String + 387 
    at 11  DragSelectCompose                   0x10175a75b        kfun:io.ktor.http.URLBuilder#<init>(io.ktor.http.URLProtocol;kotlin.String;kotlin.Int;kotlin.String?;kotlin.String?;kotlin.collections.List<kotlin.String>;io.ktor.http.Parameters;kotlin.String;kotlin.Boolean){} + 871 
    at 12  DragSelectCompose                   0x10175afef        kfun:io.ktor.http.URLBuilder#<init>(io.ktor.http.URLProtocol?;kotlin.String?;kotlin.Int;kotlin.String?;kotlin.String?;kotlin.collections.List<kotlin.String>?;io.ktor.http.Parameters?;kotlin.String?;kotlin.Boolean;kotlin.Int;kotlin.native.internal.DefaultConstructorMarker?){} + 1111 
    at 13  DragSelectCompose                   0x101764537        kfun:io.ktor.http#URLBuilder(kotlin.String){}io.ktor.http.URLBuilder + 219 
    at 14  DragSelectCompose                   0x101764403        kfun:io.ktor.http#Url(kotlin.String){}io.ktor.http.Url + 151 
    at 15  DragSelectCompose                   0x1018358cb        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.<init>$lambda$11$lambda$10$lambda$9#internal + 2831 
    at 16  DragSelectCompose                   0x10183bc9f        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.$<init>$lambda$11$lambda$10$lambda$9$FUNCTION_REFERENCE$9.invoke#internal + 139 
    at 17  DragSelectCompose                   0x10183be0b        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.$<init>$lambda$11$lambda$10$lambda$9$FUNCTION_REFERENCE$9.$<bridge-UNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}#internal + 183 
    at 18  DragSelectCompose                   0x10106d03f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 875 
    at 19  DragSelectCompose                   0x10107f42f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 187 
    at 20  DragSelectCompose                   0x101660d77        kfun:androidx.compose.material3.Surface$lambda$3#internal + 6111 
    at 21  DragSelectCompose                   0x101661587        kfun:androidx.compose.material3.$Surface$lambda$3$FUNCTION_REFERENCE$1.invoke#internal + 179 
    at 22  DragSelectCompose                   0x10166186b        kfun:androidx.compose.material3.$Surface$lambda$3$FUNCTION_REFERENCE$1.$<bridge-UNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}#internal + 183 
    at 23  DragSelectCompose                   0x10106d03f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 875 
    at 24  DragSelectCompose                   0x10107f42f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 187 
    at 25  DragSelectCompose                   0x100f8411f        kfun:androidx.compose.runtime#CompositionLocalProvider(kotlin.Array<out|androidx.compose.runtime.ProvidedValue<*>>...;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){} + 819 
    at 26  DragSelectCompose                   0x10165e6ff        kfun:androidx.compose.material3#Surface(androidx.compose.ui.Modifier?;androidx.compose.ui.graphics.Shape?;androidx.compose.ui.graphics.Color;androidx.compose.ui.graphics.Color;androidx.compose.ui.unit.Dp;androidx.compose.ui.unit.Dp;androidx.compose.foundation.BorderStroke?;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int;kotlin.Int){} + 3479 
    at 27  DragSelectCompose                   0x10183a34b        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.<init>$lambda$11$lambda$10#internal + 1027 
    at 28  DragSelectCompose                   0x10183c43f        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.$<init>$lambda$11$lambda$10$FUNCTION_REFERENCE$12.invoke#internal + 159 
    at 29  DragSelectCompose                   0x10183c5db        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.$<init>$lambda$11$lambda$10$FUNCTION_REFERENCE$12.$<bridge-UNNBNB>invoke(kotlin.Boolean;androidx.compose.runtime.Composer;kotlin.Int){}#internal + 231 
    at 30  DragSelectCompose                   0x10106d677        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 927 
    at 31  DragSelectCompose                   0x10107f543        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNNB>invoke(kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 223 
    at 32  DragSelectCompose                   0x10168feab        kfun:com.dragselectcompose.grid.LazyDragSelectGridItemScope#SelectableItem(1:0;androidx.compose.ui.Modifier?;kotlin.String?;androidx.compose.foundation.interaction.MutableInteractionSource?;kotlin.Boolean;kotlin.Function3<androidx.compose.foundation.layout.BoxScope,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>?;kotlin.Function3<androidx.compose.foundation.layout.BoxScope,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>?;kotlin.Boolean;com.dragselectcompose.grid.indicator.AnimateSelecti + 21791 
    at 33  DragSelectCompose                   0x10183ade3        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.<init>$lambda$11#internal + 2463 
    at 34  DragSelectCompose                   0x10183af8b        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.$<init>$lambda$11$FUNCTION_REFERENCE$2.invoke#internal + 175 
    at 35  DragSelectCompose                   0x10183b09f        kfun:com.dragselectcompose.demo.ComposableSingletons$PhotoGridKt.$<init>$lambda$11$FUNCTION_REFERENCE$2.$<bridge-UNNNNNB>invoke(com.dragselectcompose.grid.LazyDragSelectGridItemScope<com.dragselectcompose.demo.PhotoItem>;com.dragselectcompose.demo.PhotoItem;androidx.compose.runtime.Composer;kotlin.Int){}#internal + 255 
    at 36  DragSelectCompose                   0x10106dceb        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 971 
    at 37  DragSelectCompose                   0x10107f67b        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNNNB>invoke(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 259 
    at 38  DragSelectCompose                   0x10169a17f        kfun:com.dragselectcompose.grid.DefaultLazyDragSelectGridScope.items$lambda$4#internal + 1811 
    at 39  DragSelectCompose                   0x10169adff        kfun:com.dragselectcompose.grid.DefaultLazyDragSelectGridScope.$items$lambda$4$FUNCTION_REFERENCE$5.invoke#internal + 191 
    at 40  DragSelectCompose                   0x10169b03b        kfun:com.dragselectcompose.grid.DefaultLazyDragSelectGridScope.$items$lambda$4$FUNCTION_REFERENCE$5.$<bridge-UNNNBNB>invoke(androidx.compose.foundation.lazy.grid.LazyGridItemScope;kotlin.Int;androidx.compose.runtime.Composer;kotlin.Int){}#internal + 263 
    at 41  DragSelectCompose                   0x10106dceb        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 971 
    at 42  DragSelectCompose                   0x10107f67b        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNNNB>invoke(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 259 
    at 43  DragSelectCompose                   0x10156a857        kfun:androidx.compose.foundation.lazy.grid.LazyGridItemProviderImpl.<init>$lambda$1$lambda$0#internal + 879 
    at 44  DragSelectCompose                   0x10156b8cf        kfun:androidx.compose.foundation.lazy.grid.LazyGridItemProviderImpl.$<init>$lambda$1$lambda$0$FUNCTION_REFERENCE$6.invoke#internal + 143 
    at 45  DragSelectCompose                   0x10156ba57        kfun:androidx.compose.foundation.lazy.grid.LazyGridItemProviderImpl.$<init>$lambda$1$lambda$0$FUNCTION_REFERENCE$6.$<bridge-UNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}#internal + 183 
    at 46  DragSelectCompose                   0x10106d03f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 875 
    at 47  DragSelectCompose                   0x10107f42f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 187 
    at 48  DragSelectCompose                   0x100f8411f        kfun:androidx.compose.runtime#CompositionLocalProvider(kotlin.Array<out|androidx.compose.runtime.ProvidedValue<*>>...;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){} + 819 
    at 49  DragSelectCompose                   0x1015a48e7        kfun:androidx.compose.foundation.lazy.layout#LazyLayoutPinnableItem(kotlin.Any?;kotlin.Int;androidx.compose.foundation.lazy.layout.LazyLayoutPinnedItemList;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){} + 5463 
    at 50  DragSelectCompose                   0x10156b153        kfun:androidx.compose.foundation.lazy.grid.LazyGridItemProviderImpl.<init>$lambda$1#internal + 1983 
    at 51  DragSelectCompose                   0x10156b3e7        kfun:androidx.compose.foundation.lazy.grid.LazyGridItemProviderImpl.$<init>$lambda$1$FUNCTION_REFERENCE$4.invoke#internal + 183 
    at 52  DragSelectCompose                   0x10156b5a3        kfun:androidx.compose.foundation.lazy.grid.LazyGridItemProviderImpl.$<init>$lambda$1$FUNCTION_REFERENCE$4.$<bridge-UNNNBNB>invoke(androidx.compose.foundation.lazy.layout.IntervalList.Interval<androidx.compose.foundation.lazy.grid.LazyGridIntervalContent>;kotlin.Int;androidx.compose.runtime.Composer;kotlin.Int){}#internal + 263 
    at 53  DragSelectCompose                   0x10106dceb        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 971 
    at 54  DragSelectCompose                   0x10107f67b        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNNNB>invoke(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(kotlin.Any?;kotlin.Any?;androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 259 
    at 55  DragSelectCompose                   0x10159c687        kfun:androidx.compose.foundation.lazy.layout.DefaultLazyLayoutItemsProvider.Item#internal + 1875 
    at 56  DragSelectCompose                   0x101569bb3        kfun:androidx.compose.foundation.lazy.grid.LazyGridItemProviderImpl.Item#internal + 1663 
    at 57  DragSelectCompose                   0x10159ad83        kfun:androidx.compose.foundation.lazy.layout.DefaultDelegatingLazyLayoutItemProvider.Item#internal + 1763 
    at 58  DragSelectCompose                   0x10156c50f        kfun:androidx.compose.foundation.lazy.grid.object-1.Item#internal + 575 
    at 59  DragSelectCompose                   0x10159808b        kfun:androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory.CachedItemContent.createContentLambda$lambda$2$lambda$0#internal + 763 
    at 60  DragSelectCompose                   0x1015992d7        kfun:androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory.CachedItemContent.$createContentLambda$lambda$2$lambda$0$FUNCTION_REFERENCE$3.invoke#internal + 143 
    at 61  DragSelectCompose                   0x10159945f        kfun:androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory.CachedItemContent.$createContentLambda$lambda$2$lambda$0$FUNCTION_REFERENCE$3.$<bridge-UNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}#internal + 183 
    at 62  DragSelectCompose                   0x10106d03f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 875 
    at 63  DragSelectCompose                   0x10107f42f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 187 
    at 64  DragSelectCompose                   0x100f8411f        kfun:androidx.compose.runtime#CompositionLocalProvider(kotlin.Array<out|androidx.compose.runtime.ProvidedValue<*>>...;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){} + 819 
    at 65  DragSelectCompose                   0x1011b0d63        kfun:androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider#internal + 3143 
    at 66  DragSelectCompose                   0x1015b152f        kfun:androidx.compose.foundation.lazy.layout.LazySaveableStateHolder.SaveableStateProvider#internal + 2335 
    at 67  DragSelectCompose                   0x101598b0b        kfun:androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory.CachedItemContent.createContentLambda$lambda$2#internal + 2171 
    at 68  DragSelectCompose                   0x101599067        kfun:androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory.CachedItemContent.$createContentLambda$lambda$2$FUNCTION_REFERENCE$2.invoke#internal + 143 
    at 69  DragSelectCompose                   0x101599213        kfun:androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory.CachedItemContent.$createContentLambda$lambda$2$FUNCTION_REFERENCE$2.$<bridge-UNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}#internal + 183 
    at 70  DragSelectCompose                   0x10106d03f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 875 
    at 71  DragSelectCompose                   0x10107f42f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 187 
    at 72  DragSelectCompose                   0x10131a533        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose$lambda$0#internal + 1207 
    at 73  DragSelectCompose                   0x10131b49f        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState.$subcompose$lambda$0$FUNCTION_REFERENCE$2.invoke#internal + 143 
    at 74  DragSelectCompose                   0x10131b64b        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState.$subcompose$lambda$0$FUNCTION_REFERENCE$2.$<bridge-UNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}#internal + 183 
    at 75  DragSelectCompose                   0x10106d03f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any? + 875 
    at 76  DragSelectCompose                   0x10107f42f        kfun:androidx.compose.runtime.internal.ComposableLambdaImpl#$<bridge-NNNNB>invoke(androidx.compose.runtime.Composer;kotlin.Int){}kotlin.Any?(androidx.compose.runtime.Composer;kotlin.Any?){}kotlin.Any? + 187 
    at 77  DragSelectCompose                   0x10106b927        kfun:androidx.compose.runtime#invokeComposable(androidx.compose.runtime.Composer;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){} + 339 
    at 78  DragSelectCompose                   0x100f5f1fb        kfun:androidx.compose.runtime.ComposerImpl.doCompose$lambda$27#internal + 303 
    at 79  DragSelectCompose                   0x100f64f6f        kfun:androidx.compose.runtime.ComposerImpl.$doCompose$lambda$27$FUNCTION_REFERENCE$33.invoke#internal + 103 
    at 80  DragSelectCompose                   0x100f65103        kfun:androidx.compose.runtime.ComposerImpl.$doCompose$lambda$27$FUNCTION_REFERENCE$33.$<bridge-UNN>invoke(){}#internal + 95 
    at 81  DragSelectCompose                   0x100f8739b        kfun:androidx.compose.runtime#observeDerivedStateRecalculations(kotlin.Function1<androidx.compose.runtime.State<*>,kotlin.Unit>;kotlin.Function1<androidx.compose.runtime.State<*>,kotlin.Unit>;kotlin.Function0<0:0>){0§<kotlin.Any?>} + 1015 
    at 82  DragSelectCompose                   0x100f52c67        kfun:androidx.compose.runtime.ComposerImpl.doCompose#internal + 2247 
    at 83  DragSelectCompose                   0x100f51c33        kfun:androidx.compose.runtime.ComposerImpl#composeContent(androidx.compose.runtime.collection.IdentityArrayMap<androidx.compose.runtime.RecomposeScopeImpl,androidx.compose.runtime.collection.IdentityArraySet<kotlin.Any>?>;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){} + 431 
    at 84  DragSelectCompose                   0x100f743b7        kfun:androidx.compose.runtime.CompositionImpl#composeContent(kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){} + 535 
    at 85  DragSelectCompose                   0x100fa00bf        kfun:androidx.compose.runtime.Recomposer#composeInitial(androidx.compose.runtime.ControlledComposition;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){} + 911 
    at 86  DragSelectCompose                   0x100f589df        kfun:androidx.compose.runtime.ComposerImpl.CompositionContextImpl.composeInitial#internal + 243 
    at 87  DragSelectCompose                   0x100f589df        kfun:androidx.compose.runtime.ComposerImpl.CompositionContextImpl.composeInitial#internal + 243 
    at 88  DragSelectCompose                   0x100f738b7        kfun:androidx.compose.runtime.CompositionImpl#setContent(kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){} + 479 
    at 89  DragSelectCompose                   0x1013157f7        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto#internal + 595 
    at 90  DragSelectCompose                   0x1013153ef        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose#internal.192 + 907 
    at 91  DragSelectCompose                   0x101314fdf        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose#internal + 1287 
    at 92  DragSelectCompose                   0x1013149f3        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState#subcompose(kotlin.Any?;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){}kotlin.collections.List<androidx.compose.ui.layout.Measurable> + 2715 
    at 93  DragSelectCompose                   0x10131a047        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState.Scope.subcompose#internal + 159 
    at 94  DragSelectCompose                   0x10159f2bf        kfun:androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl#measure(kotlin.Int;androidx.compose.ui.unit.Constraints){}kotlin.collections.List<androidx.compose.ui.layout.Placeable> + 919 
    at 95  DragSelectCompose                   0x10158d80b        kfun:androidx.compose.foundation.lazy.grid.LazyMeasuredItemProvider#getAndMeasure(androidx.compose.foundation.lazy.grid.ItemIndex;kotlin.Int;androidx.compose.ui.unit.Constraints){}androidx.compose.foundation.lazy.grid.LazyGridMeasuredItem + 519 
    at 96  DragSelectCompose                   0x10158ed0b        kfun:androidx.compose.foundation.lazy.grid.LazyMeasuredLineProvider#getAndMeasure(androidx.compose.foundation.lazy.grid.LineIndex){}androidx.compose.foundation.lazy.grid.LazyGridMeasuredLine + 1251 
    at 97  DragSelectCompose                   0x10156ecab        kfun:androidx.compose.foundation.lazy.grid#measureLazyGrid(kotlin.Int;androidx.compose.foundation.lazy.grid.LazyGridItemProvider;androidx.compose.foundation.lazy.grid.LazyMeasuredLineProvider;androidx.compose.foundation.lazy.grid.LazyMeasuredItemProvider;kotlin.Int;kotlin.Int;kotlin.Int;kotlin.Int;androidx.compose.foundation.lazy.grid.LineIndex;kotlin.Int;kotlin.Float;androidx.compose.ui.unit.Constraints;kotlin.Boolean;androidx.compose.foundation.layout.Arrangement.Vertical?;androidx.compose.foundation.lay + 3507 
    at 98  DragSelectCompose                   0x10155574b        kfun:androidx.compose.foundation.lazy.grid.rememberLazyGridMeasurePolicy$lambda$6#internal + 7403 
    at 99  DragSelectCompose                   0x1015562bf        kfun:androidx.compose.foundation.lazy.grid.$rememberLazyGridMeasurePolicy$lambda$6$FUNCTION_REFERENCE$2.invoke#internal + 203 
    at 100 DragSelectCompose                   0x10155661b        kfun:androidx.compose.foundation.lazy.grid.$rememberLazyGridMeasurePolicy$lambda$6$FUNCTION_REFERENCE$2.$<bridge-NNNNB>invoke(androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScope;androidx.compose.ui.unit.Constraints){}androidx.compose.foundation.lazy.grid.LazyGridMeasureResult#internal + 187 
    at 101 DragSelectCompose                   0x101593ee3        kfun:androidx.compose.foundation.lazy.layout.LazyLayout$lambda$2$lambda$1#internal + 415 
    at 102 DragSelectCompose                   0x1015962b7        kfun:androidx.compose.foundation.lazy.layout.$LazyLayout$lambda$2$lambda$1$FUNCTION_REFERENCE$3.invoke#internal + 151 
    at 103 DragSelectCompose                   0x101596487        kfun:androidx.compose.foundation.lazy.layout.$LazyLayout$lambda$2$lambda$1$FUNCTION_REFERENCE$3.$<bridge-NNNNB>invoke(androidx.compose.ui.layout.SubcomposeMeasureScope;androidx.compose.ui.unit.Constraints){}androidx.compose.ui.layout.MeasureResult#internal + 187 
    at 104 DragSelectCompose                   0x10131accf        kfun:androidx.compose.ui.layout.LayoutNodeSubcompositionsState.object-1.measure#internal + 799 
    at 105 DragSelectCompose                   0x101339b03        kfun:androidx.compose.ui.node.InnerNodeCoordinator#measure(androidx.compose.ui.unit.Constraints){}androidx.compose.ui.layout.Placeable + 959 
    at 106 DragSelectCompose                   0x10129c703        kfun:androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure#internal + 307 
    at 107 DragSelectCompose                   0x10134387f        kfun:androidx.compose.ui.node.LayoutModifierNodeCoordinator#measure(androidx.compose.ui.unit.Constraints){}androidx.compose.ui.layout.Placeable + 467 
    at 108 DragSelectCompose                   0x10147b233        kfun:androidx.compose.foundation.layout.PaddingValuesModifier.measure#internal + 2907 
    at 109 DragSelectCompose                   0x10132b94f        kfun:androidx.compose.ui.node.BackwardsCompatNode#measure__at__androidx.compose.ui.layout.MeasureScope(androidx.compose.ui.layout.Measurable;androidx.compose.ui.unit.Constraints){}androidx.compose.ui.layout.MeasureResult + 411 
    at 110 DragSelectCompose                   0x10134387f        kfun:androidx.compose.ui.node.LayoutModifierNodeCoordinator#measure(androidx.compose.ui.unit.Constraints){}androidx.compose.ui.layout.Placeable + 467 
    at 111 DragSelectCompose                   0x10137320f        kfun:androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure$lambda$0#internal + 203 
    at 112 DragSelectCompose                   0x1013733db        kfun:androidx.compose.ui.node.LayoutNodeLayoutDelegate.$performMeasure$lambda$0$FUNCTION_REFERENCE$12.invoke#internal + 99 
    at 113 DragSelectCompose                   0x10137350b        kfun:androidx.compose.ui.node.LayoutNodeLayoutDelegate.$performMeasure$lambda$0$FUNCTION_REFERENCE$12.$<bridge-UNN>invoke(){}#internal + 95 
    at 114 DragSelectCompose                   0x10102a1a7        kfun:androidx.compose.runtime.snapshots.Snapshot.Companion#observe(kotlin.Function1<kotlin.Any,kotlin.Unit>?;kotlin.Function1<kotlin.Any,kotlin.Unit>?;kotlin.Function0<0:0>){0§<kotlin.Any?>}0:0 + 1147 
    at 115 DragSelectCompose                   0x101068f7f        kfun:androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads$lambda$3#internal + 235 
    at 116 DragSelectCompose                   0x1010695a7        kfun:androidx.compose.runtime.snapshots.SnapshotStateObserver.$observeReads$lambda$3$FUNCTION_REFERENCE$3.invoke#internal + 99 
    at 117 DragSelectCompose                   0x1010696fb        kfun:androidx.compose.runtime.snapshots.SnapshotStateObserver.$observeReads$lambda$3$FUNCTION_REFERENCE$3.$<bridge-UNN>invoke(){}#internal + 95 
    at 118 DragSelectCompose                   0x100f8739b        kfun:androidx.compose.runtime#observeDerivedStateRecalculations(kotlin.Function1<androidx.compose.runtime.State<*>,kotlin.Unit>;kotlin.Function1<androidx.compose.runtime.State<*>,kotlin.Unit>;kotlin.Function0<0:0>){0§<kotlin.Any?>} + 1015 
    at 119 DragSelectCompose                   0x101063daf        kfun:androidx.compose.runtime.snapshots.SnapshotStateObserver#observeReads(0:0;kotlin.Function1<0:0,kotlin.Unit>;kotlin.Function0<kotlin.Unit>){0§<kotlin.Any>} + 1155 
    at 120 DragSelectCompose                   0x1013aab0b        kfun:androidx.compose.ui.node.OwnerSnapshotObserver#observeReads(0:0;kotlin.Function1<0:0,kotlin.Unit>;kotlin.Function0<kotlin.Unit>){0§<androidx.compose.ui.node.OwnerScope>} + 247 
    at 121 DragSelectCompose                   0x1013aa8ef        kfun:androidx.compose.ui.node.OwnerSnapshotObserver#observeMeasureSnapshotReads(androidx.compose.ui.node.LayoutNode;kotlin.Boolean;kotlin.Function0<kotlin.Unit>){} + 443 
    at 122 DragSelectCompose                   0x1013723ef        kfun:androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure#internal + 803 
    at 123 DragSelectCompose                   0x10136632f        kfun:androidx.compose.ui.node.LayoutNodeLayoutDelegate.MeasurePassDelegate#remeasure(androidx.compose.ui.unit.Constraints){}kotlin.Boolean + 927 
    at 124 DragSelectCompose                   0x101365f47        kfun:androidx.compose.ui.node.LayoutNodeLayoutDelegate.MeasurePassDelegate#measure(androidx.compose.ui.unit.Constraints){}androidx.compose.ui.layout.Placeable + 751 
    at 125 DragSelectCompose                   0x1016573ef        kfun:androidx.compose.material3.ScaffoldLayout$lambda$6$lambda$5#internal + 15435 
```

**Comment by terrakok** [comment]
Steps were:
 - `./gradlew podspec`
 - `cd ./demo/kmm/iosApp`
 - `pod install`
 - `open ./iosApp.xcworkspace`
 - run

**Comment by jordond** [comment]
It works in AndroidStudio, not sure why the above steps wouldn't work 🤔 
image

**Comment by jordond** [comment]
After running once in Android Studio, opening in Xcode and running works.

**Comment by jordond** [comment]
I did a fresh clone and ran the following steps, and it launches for me 🤔 :

```shell
git clone git@github.com:jordond/drag-select-compose
cd drag-select-compose
./gradlew podspec
cd demo/kmm/iosApp
pod install
open ./iosApp.xcworkspace
```

**Pull request merged**
